services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: planner
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passw

  backend:
    build:
      context: .
      dockerfile: app.backend.dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: ./manage.py runserver 0.0.0.0:8000
    profiles:
      - be

volumes:
  db:
