version: "3"

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: planner
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passw

volumes:
  db:
