services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: planner
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passw

  migrations:
    image: planner
    build: .
    command: sh migrate.sh
    depends_on:
      db:
        condition: service_started
    environment:
      - DB_URL=postgresql://user:passw@db:5432/planner
      - TRIES=5

  planner:
    image: planner
    build: .
    depends_on:
      db:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    ports:
      - 8000:8000
    environment:
      - HOST=0.0.0.0
      - ENV_MODE=prod
      - SECRET_KEY=secret-prod-key
      - DB_URL=postgresql://user:passw@db:5432/planner

volumes:
  db:
